<?php
/**
 * @file
 * Make data from Adobe marketing cloud repords available if views
 *
 */

/**
 * Implements hook_menu
 */
function amcr_menu() {
  $items['amcr'] = array(
    'title' => 'test page',
    'page callback' => 'amcr_test_page',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/config/services/amcr'] = array(
    'title' => 'Adobe marketing cloud reports',
    'description' => "Configure connection to Adobe marketing cloud and edit reports parameters.",
    'page callback' => 'amcr_report_list',
    'access arguments' => array('administer amcr'),
    'weight' => 10,
    'file' => 'amcr.admin.inc',
  );
  $items['admin/config/services/amcr/add'] = array(
    'title' => 'Add report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('amcr_report_form'),
    'access arguments' => array('administer amcr'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'amcr.admin.inc',
  );

  $items['admin/config/services/amcr/remove/%amcr_report'] = array(
    'title' => 'Remove report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('amcr_admin_remove_report', 5),
    'access arguments' => array('administer amcr'),
    'file' => 'amcr.admin.inc',
  );
  $items['admin/config/services/amcr/edit/%amcr_report'] = array(
    'title' => 'Edit report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('amcr_report_form', 5),
    'access arguments' => array('administer amcr'),
    'file' => 'amcr.admin.inc',
  );
  $items['admin/config/services/amcr/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/services/amcr/settings'] = array(
    'title' => 'Settings',
    'description' => 'Configure Adobe marketing cloud connection',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('amcr_admin_form'),
    'access arguments' => array('administer amcr'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'amcr.admin.inc',
  );

  return $items;
}


/**
 * Page callbac, form amcr menu item
 */
function amcr_test_page() {
  $data_source = new AmcrReport;
  return $data_source->getData();
}


/**
 * Implements hook_permission().
 */
function amcr_permission() {
  return array(
    'administer amcr ' => array(
      'title' => t('Administer Adobe marketing cloud reports'),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function amcr_theme() {
  return array(
    'amcr_element_form' => array(
      'render element' => 'form',
      'file' => 'amcr.admin.inc',
    ),
    'amcr_metric_form' => array(
      'render element' => 'form',
      'file' => 'amcr.admin.inc',
    ),
  );
}


/**
 * Loads a report.
 *
 * @param $id
 *   The report id.
 *
 * @return
 *   An object describing the report.
 */
function amcr_report_load($id) {
  $reports = &drupal_static(__FUNCTION__);
  if (!isset($reports[$id])) {
    $report = db_query('SELECT * FROM {amcr_report_description} WHERE id = :id', array(':id' => $id))->fetchObject();

    $result = db_query('SELECT * FROM {amcr_report_definition_element} WhERE rd_id = :rd_id ORDER BY weight ASC', array(':rd_id' => $id));
    foreach ($result as $item) {
      $report->elements[$item->id] = $item;
    }

    $result = db_query('SELECT * FROM {amcr_report_definition_metric} WhERE rd_id = :rd_id ORDER BY weight ASC', array(':rd_id' => $id));
    foreach ($result as $item) {
      $report->metrics[$item->id] = $item;
    }

    $reports[$id] = $report;
  }
  return $reports[$id];
}

/**
 * Add/edit/delete a report.
 *
 * @param $edit
 *   An associative array describing the report to be added/edited/deleted.
 */
function amcr_save_report_settings($edit) {

  if (!empty($edit['id']) && !empty($edit['name'])) {
    db_update('amcr_report_description')
      ->condition('id', $edit['id'])
      ->fields(array(
        'name' => $edit['name'],
        'description' => $edit['description'],
        'report_suite_id' => $edit['report_suite_id'],
        'method' => $edit['method'],
        'date_from' => $edit['date_from'],
        'date_to' => $edit['date_to'],
        'period' => $edit['period'],
        'sort_by' => $edit['sort_by'],
      ))
      ->execute();
  }
  elseif (!empty($edit['id'])) {
    db_delete('amcr_report_description')->
      condition('id', $edit['id'])
      ->execute();
  }
  elseif (!empty($edit['name'])) {
    $edit['id'] = db_insert('amcr_report_description')
      ->fields(array(
        'name' => $edit['name'],
        'description' => $edit['description'],
        'report_suite_id' => $edit['report_suite_id'],
        'method' => $edit['method'],
        'date_from' => $edit['date_from'],
        'date_to' => $edit['date_to'],
        'period' => $edit['period'],
        'sort_by' => $edit['sort_by'],
      ))
      ->execute();
  }
}
